//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOS.Resources.ValidationErrorResource", typeof(ValidationErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentář je příliš krátký..
        /// </summary>
        internal static string ERROR_CommentTextMinLength {
            get {
                return ResourceManager.GetString("ERROR_CommentTextMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text komentáře je prázdný.
        /// </summary>
        internal static string ERROR_CommentTextRequired {
            get {
                return ResourceManager.GetString("ERROR_CommentTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název skupiny je povinný..
        /// </summary>
        internal static string ERROR_GroupNameRequired {
            get {
                return ResourceManager.GetString("ERROR_GroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět notifikace je povinný.
        /// </summary>
        internal static string ERROR_NotificationSubjectRequired {
            get {
                return ResourceManager.GetString("ERROR_NotificationSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text notifikace je povinný.
        /// </summary>
        internal static string ERROR_NotificationTextRequired {
            get {
                return ResourceManager.GetString("ERROR_NotificationTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno oboru je povinné.
        /// </summary>
        internal static string ERROR_ProgrammeNameRequired {
            get {
                return ResourceManager.GetString("ERROR_ProgrammeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartký popis je příliš dlouhý.
        /// </summary>
        internal static string ERROR_TopicDescriptionShortLength {
            get {
                return ResourceManager.GetString("ERROR_TopicDescriptionShortLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krátký popis je povinný.
        /// </summary>
        internal static string ERROR_TopicDescriptionShortRequired {
            get {
                return ResourceManager.GetString("ERROR_TopicDescriptionShortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název je povinný.
        /// </summary>
        internal static string ERROR_TopicNameRequired {
            get {
                return ResourceManager.GetString("ERROR_TopicNameRequired", resourceCulture);
            }
        }
    }
}
